DROP TABLE IF EXISTS bid;

CREATE TABLE bid (
	userid BIGINT,
	itemname VARCHAR(30),
	bid INTEGER NOT NULL,
	reserve INTEGER NOT NULL,
	CONSTRAINT fk_perk FOREIGN KEY(itemname) REFERENCES item(name) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_user FOREIGN KEY(userid) REFERENCES discorduser(id) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE bid ADD CONSTRAINT pepk PRIMARY KEY(userid,itemname);
