DROP TABLE IF EXISTS pathbids;
DROP TABLE IF EXISTS racebids;
DROP TABLE IF EXISTS perkbids;

CREATE TABLE pathbids (
	userid BIGINT,
	pathname CHAR(1),
	bid INTEGER NOT NULL,
	priority  SMALLINT NOT NULL,
	CONSTRAINT fk_path FOREIGN KEY(pathname) REFERENCES paths(name) ON DELETE CASCADE ON UPDATE CASCADE,	
	CONSTRAINT fk_user FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE pathbids ADD CONSTRAINT papk PRIMARY KEY(userid,pathname,priority);

CREATE TABLE racebids (
	userid BIGINT,
	racename VARCHAR(12),
	bid INTEGER NOT NULL,
	CONSTRAINT fk_race FOREIGN KEY(racename) REFERENCES races(name) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_user FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);


ALTER TABLE racebids ADD CONSTRAINT rapk PRIMARY KEY(userid,racename);

CREATE TABLE perkbids (
	userid BIGINT,
	perkname VARCHAR(30),
	bid INTEGER NOT NULL,
	reserve INTEGER NOT NULL,
	CONSTRAINT fk_perk FOREIGN KEY(perkname) REFERENCES perks(name) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_user FOREIGN KEY(userid) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE perkbids ADD CONSTRAINT pepk PRIMARY KEY(userid,perkname);
